baseUrl = "https://www.gcppodcast.com"
languageCode = "en-us"
title = "Google Cloud Podcast"
theme = "gcppodcast2018"

relativeURLs = true

paginate = 9

#Site Params
[params]
  description = "The Google Cloud Podcast, coming to you every week. Discussing everything on Google Cloud from App Engine to Big Query."
  logo = "images/site_logo.png"
  twitterUser = "gcppodcast"
  twitterURL = "https://twitter.com/gcppodcast"
  googlePlusURL = "http://google.com/+gcppodcast"
  redditURL = "https://www.reddit.com/r/gcppodcast/"
  copyright = "Copyright 2021 Google Inc."
  episodeBucket = "https://eps-dot-gcppodcast.appspot.com/dl"
  rssFeed = "https://feeds.feedburner.com/GcpPodcast"
  itunesURL = "https://itunes.apple.com/us/podcast/google-cloud-platform-podcast/id1053299163"
  stitcherURL = "http://www.stitcher.com/podcast/google-cloud-platform-podcast?refid=stpr"
  googleMusicURL = "https://play.google.com/music/m/Iqkxpgvsbeejmz6d3g77qabpvme?t=Google_Cloud_Platform_Podcast"
  googlePodcastsURL = "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5mZWVkYnVybmVyLmNvbS9HY3BQb2RjYXN0"
  emailFBURL = "https://feedburner.google.com/fb/a/mailverify?uri=GcpPodcast&loc=en_US"
  youtubeURL = "https://www.youtube.com/playlist?list=PLIivdWyY5sqJOTOszXDZh3XustjvTsrmQ"
  spotifyURL = "https://open.spotify.com/show/36qjuTreaI4bIjd3R9CDXe"


[taxonomies]
  category = "categories"


[outputs]
home = [ "HTML", "RSS", "JSON"]
