baseUrl = "https://gcppodcast-dev.appspot.com/"
languageCode = "en-us"
title = "Google Cloud Platform Podcast"
theme = "gcppodcast2018"

relativeURLs = true

paginate = 9

#Site Params
[params]
  description = "The Google Cloud Platform Podcast, coming to you every week. Discussing everything from on Google Cloud Platform from App Engine to Big Query."
  logo = "images/site_logo.png"
  twitterUser = "gcppodcast"
  twitterURL = "https://twitter.com/gcppodcast"
  googlePlusURL = "http://google.com/+gcppodcast"
  redditURL = "https://www.reddit.com/r/gcppodcast/"
  copyright = "Copyright 2015 Google Inc."
  episodeBucket = "https://eps-dot-gcppodcast.appspot.com/dl"
  rssFeed = "https://feeds.feedburner.com/GcpPodcast"
  itunesURL = "https://itunes.apple.com/us/podcast/google-cloud-platform-podcast/id1053299163"
  stitcherURL = "http://www.stitcher.com/podcast/google-cloud-platform-podcast?refid=stpr"
  googleMusicURL = "https://play.google.com/music/m/Iqkxpgvsbeejmz6d3g77qabpvme?t=Google_Cloud_Platform_Podcast"
  emailFBURL = "https://feedburner.google.com/fb/a/mailverify?uri=GcpPodcast&loc=en_US"
  youtubeURL = "https://www.youtube.com/playlist?list=PLIivdWyY5sqJOTOszXDZh3XustjvTsrmQ"


[taxonomies]
  category = "categories"


[outputs]
home = [ "HTML", "RSS", "JSON"]
